kind: pipeline
type: kubernetes
name: default

steps:
  - name: build hugo site
    image: klakegg/hugo:ext-alpine
    commands:
      - hugo

  - name: docker build and push
    image: plugins/docker
    settings:
      registry: harbor.rustybower.com
      repo: harbor.rustybower.com/hugo/hugo-site
      tags: latest
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
