kind: pipeline
type: kubernetes
name: default

clone:
  depth: 1
  submodules: true  # Ensures your Hugo theme (as a submodule) is cloned properly

steps:
  - name: init submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  #- name: debug ls
    #image: alpine
    #commands:
      #- ls -al themes/
      #- cat .gitmodules || true

  - name: docker build and push
    image: plugins/docker
    settings:
      registry: harbor.rustybower.com
      repo: harbor.rustybower.com/hugo/hugo-site
      tags:
        - latest
      dockerfile: Dockerfile
      build_args:
        - HUGO_BASEURL=https://www.rustybower.com/
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password

  - name: deploy
    image: bitnami/kubectl:latest
    commands:
      - echo "$KUBECONFIG_CONTENT" > /tmp/kubeconfig
      - kubectl --kubeconfig=/tmp/kubeconfig rollout restart deployment/hugo -n hugo
    environment:
      KUBECONFIG_CONTENT:
        from_secret: rustycloud_kubeconfig

  #- name: debug hugo build output
    #image: alpine
    #commands:
      #- ls -alR /site/public
      #- ls -alR /src/public
