kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker build and push
    image: plugins/docker
    settings:
      registry: harbor.rustybower.com
      repo: harbor.rustybower.com/hugo/hugo-site
      tags:
        - latest
      dockerfile: Dockerfile
      build_args:
        - HUGO_BASEURL=https://www.rustybower.com/
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
